apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__-service
spec:
  type: NodePort
  selector:
    app: __APP_NAME__
    version: blue 
  ports:
    - protocol: TCP
      port: 80
      targetPort: __TARGET_PORT__
      nodePort: __NODE_PORT__ 